name: Deploy
run-name: Deploy
on:
  push:
    branches:
      - master
      - workflow-update
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh command
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_ID_RSA }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ./deploy/deploy-bing-chat-bot.sh
            
            # Update Cookies
            COOKIE_2=$(cat <<===TEXT_FILE_ENDS_HERE===
            ${{ secrets.COOKIE_2 }}
            ===TEXT_FILE_ENDS_HERE===
            )
            ./deploy/deploy-bing-chat-cookies.sh "$COOKIE_2" 2
            
            COOKIE_3=$(cat <<===TEXT_FILE_ENDS_HERE===
            ${{ secrets.COOKIE_3 }}
            ===TEXT_FILE_ENDS_HERE===
            )
            ./deploy/deploy-bing-chat-cookies.sh "$COOKIE_3" 3
