name: Deploy
run-name: Deploy
on:
  push:
    branches:
      - master
      - workflow-update
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh command
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_ID_RSA }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            ./deploy-bing-chat-bot.sh
            echo ${{ secrets.COOKIE_2 }} > output.txt
